# Generated by Django 3.2.12 on 2022-03-19 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('site_url', models.URLField()),
                ('contact_mail', models.EmailField(max_length=254)),
                ('admin_mail', models.EmailField(max_length=254)),
                ('is_paid', models.BooleanField(default=False)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('company_mail', models.EmailField(max_length=254)),
                ('company_owned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='company_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.companyadmin'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
