# Generated by Django 3.2.12 on 2022-03-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220319_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
