# Generated by Django 3.2.12 on 2022-03-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_companyadmin_is_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('product_site_url', models.URLField(blank=True, null=True)),
                ('keywords', models.TextField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
