# Generated by Django 3.2.12 on 2022-03-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
