# Generated by Django 3.2.12 on 2022-03-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_productkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkeyword',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
