# Generated by Django 3.2.12 on 2022-05-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_productkeyword_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
    ]
