# Generated by Django 3.2.12 on 2022-05-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_product_slug'),
        ('athena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='users.product'),
            preserve_default=False,
        ),
    ]
