# Generated by Django 3.2.12 on 2022-06-26 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_product_slug'),
        ('athena', '0003_attributeextract_productinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeextract',
            name='generated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributeextract',
            name='hit_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributeextract',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.product'),
            preserve_default=False,
        ),
    ]
