# Generated by Django 3.2.12 on 2022-06-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_product_slug'),
        ('athena', '0004_auto_20220626_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttributeExtract',
            new_name='AttributeHitScore',
        ),
    ]
