# Generated by Django 3.2.12 on 2022-06-30 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0005_rename_attributeextract_attributehitscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRate',
            fields=[
                ('productinsight_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='athena.productinsight')),
                ('new_rate', models.FloatField()),
                ('hit_rate', models.FloatField()),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('athena.productinsight',),
        ),
    ]
