# Generated by Django 3.2.12 on 2022-06-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0006_newrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrate',
            name='new_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
