# Generated by Django 3.2.12 on 2022-06-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athena', '0007_alter_newrate_new_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrate',
            name='produced',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
